FI-2886:  Allow Sub Organizations
inferno-framework/service-base-url-test-kit pull request #36
Opened 2024-11-01 16:57 UTC by emichaud998

# Summary
Updated the service base URL test kit to allow for tiers of organizations according to CCG [clarification to ‘(b) Maintenance of certification requirements—(2) Service base URL publication’ ](https://www.healthit.gov/condition-ccg/application-programming-interfaces/#a-46621). Now, if an Organization does not have the `endpoint` field populated, it will check to see if the Organization has the `partOf` field populated, and if it does, it will check that the referenced parent Organization has the `endpoint` field populated.

# Testing Guidance
Run spec tests and ensure they pass, and run locally and test against this bundle:

`{
  "resourceType": "Bundle",
  "id": "example2",
  "type": "collection",
  "timestamp": "2023-09-05T20:18:52.638960-07:00",
  "entry": [
    {
      "fullUrl": "https://ehr.organization.com/Organization/examplehealth",
      "resource": {
        "resourceType": "Organization",
        "id": "examplehealth",
        "extension": [
          {
            "extension": [
              {
                "url": "brandLogo",
                "valueUrl": "https://organization.org/examplehealth/logo/main.1024x1024.png"
              }
            ],
            "url": "http://hl7.org/fhir/StructureDefinition/organization-brand"
          },
          {
            "extension": [
              {
                "url": "portalName",
                "valueString": "My ExampleHealth Portal"
              },
              {
                "url": "portalLogo",
                "valueUrl": "https://organization.org/examplehealth/logo/main.1024x1024.png"
              },
              {
                "url": "portalUrl",
                "valueUrl": "https://organization.org/examplehealth/patient-portal-url"
              },
              {
                "url": "portalEndpoint",
                "valueReference": {
                  "reference": "Endpoint/examplehealth-r4",
                  "display": "FHIR R4 Endpoint for ExampleHealth Brand"
                }
              },
              {
                "url": "portalEndpoint",
                "valueReference": {
                  "reference": "Endpoint/examplehealth-r2",
                  "display": "FHIR R2 Endpoint for ExampleHealth Brand"
                }
              }
            ],
            "url": "http://hl7.org/fhir/StructureDefinition/organization-portal"
          }
        ],
        "identifier": [
          {
            "system": "urn:ietf:rfc:3986",
            "value": "https://examplehealth.org"
          }
        ],
        "active": true,
        "type": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                "code": "prov",
                "display": "Healthcare Provider"
              }
            ]
          }
        ],
        "name": "ExampleHealth",
        "alias": [
          "GoodHealth Hospital",
          "GoodHealth Mental Health"
        ],
        "telecom": [
          {
            "system": "url",
            "value": "https://health.organization.com"
          }
        ],
        "address": [
          {
            "city": "Madison",
            "state": "WI",
            "country": "US"
          },
          {
            "city": "Anamosa",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Cedar Rapids",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Des Moines",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Dubuque",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Fort Dodge",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Grinnell",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Marshalltown",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Peoria",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Pekin",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Muscatine",
            "state": "IA",
            "country": "US"
          },
          {
            "city": "Sioux City",
            "state": "IA",
            "country": "US"
          }
        ],
        "endpoint": [
          {
            "reference": "Endpoint/examplehealth-r2",
            "display": "FHIR R2 Endpoint for ExampleHealth Brand"
          },
          {
            "reference": "Endpoint/examplehealth-r4",
            "display": "FHIR R4 Endpoint for ExampleHealth Brand"
          }
        ]
      }
    },
    {
      "fullUrl": "https://ehr.organization.com/Organization/ehchospital",
      "resource": {
        "resourceType": "Organization",
        "id": "ehchospital",
        "extension": [
          {
            "extension": [
              {
                "url": "brandLogo",
                "valueUrl": "data:image/svg+xml;base64,PHN2ZyB0aXRsZT0iU3Rld2FydCBNZW1vcmlhbCBIb3Nw...+IDwvc3ZnPgo="
              }
            ],
            "url": "http://hl7.org/fhir/StructureDefinition/organization-brand"
          }
        ],
        "identifier": [
          {
            "system": "urn:ietf:rfc:3986",
            "value": "https://ehchospital.organization.org"
          }
        ],
        "active": true,
        "type": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                "code": "prov",
                "display": "Healthcare Provider"
              }
            ]
          }
        ],
        "name": "ExampleHealth Community Hospital",
        "alias": [
          "GoodHealth Madison"
        ],
        "telecom": [
          {
            "system": "url",
            "value": "https://www.ehchospital.organization.com"
          }
        ],
        "address": [
          {
            "city": "Lake City",
            "state": "IA",
            "country": "US"
          }
        ],
        "partOf": {
          "reference": "Organization/examplehealth"
        }
      }
    },
    {
      "fullUrl": "https://ehr.organization.com/Organization/ehpmadison",
      "resource": {
        "resourceType": "Organization",
        "id": "ehpmadison",
        "extension": [
          {
            "extension": [
              {
                "url": "brandLogo",
                "valueUrl": "https://ehpmadison.organization.com/logo.png"
              }
            ],
            "url": "http://hl7.org/fhir/StructureDefinition/organization-brand"
          }
        ],
        "identifier": [
          {
            "system": "urn:ietf:rfc:3986",
            "value": "https://ehpmadison.organization.com"
          }
        ],
        "active": true,
        "type": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                "code": "prov",
                "display": "Healthcare Provider"
              }
            ]
          }
        ],
        "name": "ExampleHealth Physicians of Madison",
        "alias": [
          "GoodHealth Madison"
        ],
        "telecom": [
          {
            "system": "url",
            "value": "https://www.ehpmadison.organization.com"
          }
        ],
        "address": [
          {
            "city": "Madison",
            "state": "WI",
            "country": "US"
          }
        ],
        "partOf": {
          "reference": "Organization/examplehealth"
        }
      }
    },
    {
      "fullUrl": "https://ehr.organization.com/Endpoint/examplehealth-r2",
      "resource": {
        "resourceType": "Endpoint",
        "id": "examp [...]

2024-11-01 17:07 UTC, arscan commented
I was originally thinking that perhaps this should be a recursive thing, where a parent or a grandparent or a great-grandparent could have the endpoint information.  But my understanding is that the goal of this is to ensure that User Access Brand conformant bundles are considered conformant here as well, and User Access brands doesn't allow heirarchies larger than two (parent and child), so this implementation seems fine to me:

https://build.fhir.org/ig/HL7/smart-app-launch/StructureDefinition-user-access-brand.html
> 0..1 MS `partOf` Conveys that an affiliate Brand response for providing this Brand’s user access. The hierarchy of “access provided by” links SHALL NOT exceed a depth of two (i.e., a Brand either includes portal details or links directly to a Brand that provides them).

Just noting that we considered this and decided to not have the test allow it due to the language in the clarification and the language in the User Access Brands spec.

2024-11-01 18:00 UTC, emichaud998 commented
> I was originally thinking that perhaps this should be a recursive thing, where a parent or a grandparent or a great-grandparent could have the endpoint information. But my understanding is that the goal of this is to ensure that User Access Brand conformant bundles are considered conformant here as well, and User Access brands doesn't allow heirarchies larger than two (parent and child), so this implementation seems fine to me:
> 
> https://build.fhir.org/ig/HL7/smart-app-launch/StructureDefinition-user-access-brand.html
> 
> > 0..1 MS `partOf` Conveys that an affiliate Brand response for providing this Brand’s user access. The hierarchy of “access provided by” links SHALL NOT exceed a depth of two (i.e., a Brand either includes portal details or links directly to a Brand that provides them).
> 
> Just noting that we considered this and decided to not have the test allow it due to the language in the clarification and the language in the User Access Brands spec.

I agree and was thinking of doing the same thing, but I saw that a requirement is that it cannot exceed a depth of 2, so I felt that this approach made more sense.

2024-11-01 18:30 UTC, arscan requested changes
I tried the tests against the User-access Brands examples (which has an example of only the parent org having an endpoint), as well as our regular service base url tests, and it looks good to me.

But please make sure that any descriptions that need updating are updated.  The one spot I found was here:  https://github.com/inferno-framework/service-base-url-test-kit/blob/5f2afbaa4593e4f5bc1436a1239cff745d85e655/lib/service_base_url_test_kit/service_base_url_validate_group.rb#L280-L288

2024-11-06 15:28 UTC, arscan approved these changes

2024-11-06 15:29 UTC, merged